[package]
name = "brainrust"
version = "0.1.4"
authors = ["Emil Englesson <englesson.emil@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5", features = ["cargo", "color", "suggestions", "wrap_help"] }

[dev-dependencies]
paste = "1.0"

