[package]
name = "brainrust"
version = "0.1.0"
authors = ["Emil Englesson <englesson.emil@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "2.33.0", features = ["color", "wrap_help", "suggestions"] }
itertools = "0.8.2"
