[package]
name = "brainrust"
version = "0.1.4"
authors = ["Emil Englesson <englesson.emil@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5", features = ["cargo", "color", "wrap_help", "suggestions"] }
itertools = "0.14"
