name: Rust

on: [push, pull_request]

jobs:
  build:
    name: "build"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  fmt:
    name: "fmt"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check formatting with rustfmt
      run: cargo fmt --all -- --check
